-- ============================================================
-- sp_log_pipeline_event.sql
-- Purpose: Helper procedure to log pipeline executions easily
-- Run as: EV_DEMO_ADMIN
-- Prerequisite: GRANT CREATE PROCEDURE ON SCHEMA AUDIT TO ROLE EV_DEMO_ADMIN
-- ============================================================
-- USAGE:
--   CALL EV_POPULATION_DB.AUDIT.SP_LOG_PIPELINE_EVENT(
--       'PIPELINE_NAME', 'LAYER',
--       'SOURCE_TABLE', 'TARGET_TABLE',
--       'OPERATION', ROWS_AFFECTED, 'STATUS', 'ERROR_MSG_OR_NULL',
--       STARTED_TIMESTAMP, COMPLETED_TIMESTAMP
--   );
--
-- EXAMPLE:
--   CALL EV_POPULATION_DB.AUDIT.SP_LOG_PIPELINE_EVENT(
--       'SNOWPIPE_EV_INGEST', 'BRONZE',
--       '@EV_RAW_STAGE/ev_population/', 'BRONZE.RAW_EV_POPULATION',
--       'INSERT_FLATTEN', 22183, 'SUCCESS', NULL,
--       '2026-05-23 07:43:00'::TIMESTAMP_NTZ, '2026-05-23 07:43:55'::TIMESTAMP_NTZ
--   );
-- ============================================================

USE ROLE EV_DEMO_ADMIN;
USE WAREHOUSE EV_DEMO_WH;
USE SCHEMA EV_POPULATION_DB.AUDIT;

CREATE OR REPLACE PROCEDURE SP_LOG_PIPELINE_EVENT(
    P_PIPELINE_NAME VARCHAR,
    P_LAYER VARCHAR,
    P_SOURCE_TABLE VARCHAR,
    P_TARGET_TABLE VARCHAR,
    P_OPERATION VARCHAR,
    P_ROWS_AFFECTED NUMBER,
    P_STATUS VARCHAR,
    P_ERROR_MESSAGE VARCHAR,
    P_STARTED_AT TIMESTAMP_NTZ,
    P_COMPLETED_AT TIMESTAMP_NTZ
)
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    LET duration NUMBER := DATEDIFF('SECOND', :P_STARTED_AT, :P_COMPLETED_AT);
    INSERT INTO EV_POPULATION_DB.AUDIT.AUDIT_PIPELINE_LOG (
        PIPELINE_NAME, LAYER, SOURCE_TABLE, TARGET_TABLE, OPERATION,
        ROWS_AFFECTED, STATUS, ERROR_MESSAGE, STARTED_AT, COMPLETED_AT, DURATION_SECONDS, EXECUTED_BY
    )
    VALUES (
        :P_PIPELINE_NAME, :P_LAYER, :P_SOURCE_TABLE, :P_TARGET_TABLE, :P_OPERATION,
        :P_ROWS_AFFECTED, :P_STATUS, :P_ERROR_MESSAGE, :P_STARTED_AT, :P_COMPLETED_AT,
        :duration, CURRENT_ROLE()
    );
    RETURN 'Logged: ' || :P_PIPELINE_NAME || ' | ' || :P_STATUS;
END;
