-- ============================================================
-- task_dag_pipeline.sql
-- Purpose: End-to-end pipeline orchestration with Task DAG
-- Run as: EV_DEMO_ADMIN
-- ============================================================
-- DAG STRUCTURE:
--
--   TSK_PIPELINE_ROOT (SCHEDULE = 60 MIN)
--       │
--       ├── TSK_BRONZE_EV_FLATTEN [AFTER ROOT]
--       │     Flatten Snowpipe staging → Bronze
--       │     WHEN: STM_RAW_EV_STAGING has data
--       │
--       ├── TSK_BRONZE_PG_MERGE [AFTER ROOT]
--       │     CDC stream → PG_BRONZE (MERGE)
--       │     WHEN: PG_STM_CHARGING_STATIONS has data
--       │
--       └── TSK_DQ_GATE [AFTER EV_FLATTEN + PG_MERGE]
--             Runs all DQ procs + sends email alert on failure
--
-- BEHAVIOR:
--   - Root fires every 60 min
--   - Children only run if their stream has data (zero cost otherwise)
--   - DQ gate waits for BOTH Bronze tasks to complete
--   - If a parent fails, children don't fire
--
-- RESUME:  Children first, root last
-- SUSPEND: Root only (stops entire pipeline)
-- ============================================================

USE ROLE EV_DEMO_ADMIN;
USE WAREHOUSE EV_DEMO_WH;
USE SCHEMA EV_POPULATION_DB.UTILITIES;

CREATE OR REPLACE TASK TSK_PIPELINE_ROOT
    WAREHOUSE = EV_DEMO_WH
    SCHEDULE = '60 MINUTE'
AS
    SELECT 1;

CREATE OR REPLACE TASK TSK_BRONZE_EV_FLATTEN
    WAREHOUSE = EV_DEMO_WH
    AFTER TSK_PIPELINE_ROOT
    WHEN SYSTEM$STREAM_HAS_DATA('EV_POPULATION_DB.BRONZE.STM_RAW_EV_STAGING')
AS
INSERT INTO EV_POPULATION_DB.BRONZE.RAW_EV_POPULATION (RAW_DATA, SOURCE_FILE_NAME, SOURCE_FILE_ROW, LOADED_AT)
SELECT f.value, stg.SOURCE_FILE_NAME, f.index, CURRENT_TIMESTAMP()
FROM EV_POPULATION_DB.BRONZE.STM_RAW_EV_STAGING stg,
    LATERAL FLATTEN(input => stg.RAW_FILE:data) f
WHERE stg.METADATA$ACTION = 'INSERT';

CREATE OR REPLACE TASK TSK_BRONZE_PG_MERGE
    WAREHOUSE = EV_DEMO_WH
    AFTER TSK_PIPELINE_ROOT
    WHEN SYSTEM$STREAM_HAS_DATA('EV_POPULATION_DB.PG_RAW_SOURCE.PG_STM_CHARGING_STATIONS')
AS
MERGE INTO EV_POPULATION_DB.PG_BRONZE.PG_CHARGING_STATIONS AS tgt
USING (
    SELECT STATION_ID, STATION_NAME, CITY, COUNTY, STATE, ZIP_CODE,
        CONNECTOR_TYPE, POWER_LEVEL_KW, NETWORK, NUM_PORTS, STATUS,
        LATITUDE, LONGITUDE, LAST_UPDATED,
        METADATA$ACTION AS CDC_ACTION, METADATA$ISUPDATE AS IS_UPDATE
    FROM EV_POPULATION_DB.PG_RAW_SOURCE.PG_STM_CHARGING_STATIONS
) AS src
ON tgt.STATION_ID = src.STATION_ID
WHEN MATCHED AND src.CDC_ACTION = 'DELETE' AND src.IS_UPDATE = FALSE THEN
    UPDATE SET tgt.IS_DELETED = TRUE, tgt.MERGED_AT = CURRENT_TIMESTAMP()
WHEN MATCHED AND src.CDC_ACTION = 'INSERT' AND src.IS_UPDATE = TRUE THEN
    UPDATE SET tgt.STATION_NAME = src.STATION_NAME, tgt.CITY = src.CITY,
        tgt.COUNTY = src.COUNTY, tgt.STATE = src.STATE, tgt.ZIP_CODE = src.ZIP_CODE,
        tgt.CONNECTOR_TYPE = src.CONNECTOR_TYPE, tgt.POWER_LEVEL_KW = src.POWER_LEVEL_KW,
        tgt.NETWORK = src.NETWORK, tgt.NUM_PORTS = src.NUM_PORTS, tgt.STATUS = src.STATUS,
        tgt.LATITUDE = src.LATITUDE, tgt.LONGITUDE = src.LONGITUDE,
        tgt.LAST_UPDATED = src.LAST_UPDATED, tgt.IS_DELETED = FALSE, tgt.MERGED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED AND src.CDC_ACTION = 'INSERT' THEN
    INSERT (STATION_ID, STATION_NAME, CITY, COUNTY, STATE, ZIP_CODE, CONNECTOR_TYPE,
            POWER_LEVEL_KW, NETWORK, NUM_PORTS, STATUS, LATITUDE, LONGITUDE,
            LAST_UPDATED, MERGED_AT, IS_DELETED)
    VALUES (src.STATION_ID, src.STATION_NAME, src.CITY, src.COUNTY, src.STATE, src.ZIP_CODE,
            src.CONNECTOR_TYPE, src.POWER_LEVEL_KW, src.NETWORK, src.NUM_PORTS, src.STATUS,
            src.LATITUDE, src.LONGITUDE, src.LAST_UPDATED, CURRENT_TIMESTAMP(), FALSE);

CREATE OR REPLACE TASK TSK_DQ_GATE
    WAREHOUSE = EV_DEMO_WH
    AFTER TSK_BRONZE_EV_FLATTEN, TSK_BRONZE_PG_MERGE
AS
BEGIN
    CALL EV_POPULATION_DB.AUDIT.SP_DQ_CHECK_BRONZE_EV();
    CALL EV_POPULATION_DB.AUDIT.SP_DQ_CHECK_BRONZE_PG();
    CALL EV_POPULATION_DB.AUDIT.SP_DQ_CHECK_COMPREHENSIVE();
    CALL EV_POPULATION_DB.AUDIT.SP_DQ_ALERT_ON_FAILURES();
END;

-- RESUME (children first, root last):
-- ALTER TASK TSK_DQ_GATE RESUME;
-- ALTER TASK TSK_BRONZE_EV_FLATTEN RESUME;
-- ALTER TASK TSK_BRONZE_PG_MERGE RESUME;
-- ALTER TASK TSK_PIPELINE_ROOT RESUME;

-- SUSPEND (root only stops everything):
-- ALTER TASK TSK_PIPELINE_ROOT SUSPEND;
