-- ============================================================
-- 01_roles_and_grants.sql
-- Purpose: Create functional roles and wire role hierarchy
-- Run as: USERADMIN (roles) + SECURITYADMIN (grants)
-- ============================================================

-- STEP 1: Create Roles
USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS EV_DEMO_ADMIN
    COMMENT = 'Full control over EV demo database and objects';

CREATE ROLE IF NOT EXISTS EV_DEMO_ENGINEER
    COMMENT = 'Read-write access to Bronze/Silver/Gold layers, runs pipelines';

CREATE ROLE IF NOT EXISTS EV_DEMO_ANALYST
    COMMENT = 'Read-only access to Silver and Gold layers for reporting';

-- STEP 2: Role Hierarchy
-- ANALYST → ENGINEER → ADMIN → SYSADMIN
USE ROLE SECURITYADMIN;

GRANT ROLE EV_DEMO_ANALYST TO ROLE EV_DEMO_ENGINEER;
GRANT ROLE EV_DEMO_ENGINEER TO ROLE EV_DEMO_ADMIN;
GRANT ROLE EV_DEMO_ADMIN TO ROLE SYSADMIN;

-- STEP 3: Assign admin role to your user (uncomment and replace)
-- GRANT ROLE EV_DEMO_ADMIN TO USER YOUR_USERNAME;

-- STEP 4: Database & Schema Grants
GRANT USAGE ON DATABASE EV_POPULATION_DB TO ROLE EV_DEMO_ENGINEER;
GRANT USAGE ON DATABASE EV_POPULATION_DB TO ROLE EV_DEMO_ANALYST;

GRANT USAGE ON ALL SCHEMAS IN DATABASE EV_POPULATION_DB TO ROLE EV_DEMO_ENGINEER;
GRANT USAGE ON SCHEMA EV_POPULATION_DB.SILVER TO ROLE EV_DEMO_ANALYST;
GRANT USAGE ON SCHEMA EV_POPULATION_DB.GOLD TO ROLE EV_DEMO_ANALYST;

-- STEP 5: Warehouse Grants
GRANT USAGE ON WAREHOUSE EV_DEMO_WH TO ROLE EV_DEMO_ADMIN;
GRANT USAGE ON WAREHOUSE EV_DEMO_WH TO ROLE EV_DEMO_ENGINEER;
GRANT USAGE ON WAREHOUSE EV_DEMO_WH TO ROLE EV_DEMO_ANALYST;

-- STEP 6: Schema Create Privileges for ENGINEER
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE FUNCTION, CREATE PROCEDURE
    ON SCHEMA EV_POPULATION_DB.BRONZE TO ROLE EV_DEMO_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE FUNCTION, CREATE PROCEDURE
    ON SCHEMA EV_POPULATION_DB.SILVER TO ROLE EV_DEMO_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE FUNCTION, CREATE PROCEDURE
    ON SCHEMA EV_POPULATION_DB.GOLD TO ROLE EV_DEMO_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW
    ON SCHEMA EV_POPULATION_DB.AUDIT TO ROLE EV_DEMO_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE FUNCTION
    ON SCHEMA EV_POPULATION_DB.UTILITIES TO ROLE EV_DEMO_ENGINEER;

-- STEP 7: Future Grants (auto-apply to new objects)
GRANT SELECT ON FUTURE TABLES IN SCHEMA EV_POPULATION_DB.BRONZE TO ROLE EV_DEMO_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA EV_POPULATION_DB.SILVER TO ROLE EV_DEMO_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA EV_POPULATION_DB.GOLD TO ROLE EV_DEMO_ENGINEER;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA EV_POPULATION_DB.AUDIT TO ROLE EV_DEMO_ENGINEER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA EV_POPULATION_DB.SILVER TO ROLE EV_DEMO_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EV_POPULATION_DB.GOLD TO ROLE EV_DEMO_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA EV_POPULATION_DB.SILVER TO ROLE EV_DEMO_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA EV_POPULATION_DB.GOLD TO ROLE EV_DEMO_ANALYST;

-- STEP 8: Task & CDC Grants
USE ROLE ACCOUNTADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE EV_DEMO_ADMIN;

USE ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA EV_POPULATION_DB.PG_RAW_SOURCE TO ROLE EV_DEMO_ENGINEER;
GRANT USAGE ON SCHEMA EV_POPULATION_DB.PG_BRONZE TO ROLE EV_DEMO_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EV_POPULATION_DB.PG_RAW_SOURCE TO ROLE EV_DEMO_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EV_POPULATION_DB.PG_BRONZE TO ROLE EV_DEMO_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA EV_POPULATION_DB.PG_BRONZE TO ROLE EV_DEMO_ANALYST;
