-- ============================================================
-- agg_ev_by_region.sql
-- Purpose: Regional EV adoption metrics (state/county/city)
-- Method: Dynamic Table on GOLD.FACT_EV_REGISTRATIONS
-- ============================================================

USE ROLE EV_DEMO_ADMIN;
USE WAREHOUSE EV_DEMO_WH;

CREATE OR REPLACE DYNAMIC TABLE EV_POPULATION_DB.GOLD.AGG_EV_BY_REGION
    TARGET_LAG = '1 hour'
    WAREHOUSE = EV_DEMO_WH
AS
SELECT
    STATE,
    COUNTY,
    CITY,
    COUNT(*) AS TOTAL_EVS,
    COUNT_IF(EV_TYPE_SHORT = 'BEV') AS BEV_COUNT,
    COUNT_IF(EV_TYPE_SHORT = 'PHEV') AS PHEV_COUNT,
    ROUND(BEV_COUNT * 100.0 / TOTAL_EVS, 1) AS BEV_PERCENTAGE,
    COUNT_IF(IS_CAFV_ELIGIBLE) AS CAFV_ELIGIBLE_COUNT,
    ROUND(CAFV_ELIGIBLE_COUNT * 100.0 / TOTAL_EVS, 1) AS CAFV_ELIGIBLE_PCT,
    AVG(ELECTRIC_RANGE) AS AVG_ELECTRIC_RANGE,
    COUNT(DISTINCT MAKE) AS UNIQUE_MANUFACTURERS,
    COUNT(DISTINCT MODEL) AS UNIQUE_MODELS
FROM EV_POPULATION_DB.GOLD.FACT_EV_REGISTRATIONS
GROUP BY STATE, COUNTY, CITY;
