-- ============================================================
-- agg_ev_by_make_model.sql
-- Purpose: Manufacturer market share and model performance
-- Method: Dynamic Table on GOLD.FACT_EV_REGISTRATIONS
-- ============================================================

USE ROLE EV_DEMO_ADMIN;
USE WAREHOUSE EV_DEMO_WH;

CREATE OR REPLACE DYNAMIC TABLE EV_POPULATION_DB.GOLD.AGG_EV_BY_MAKE_MODEL
    TARGET_LAG = '1 hour'
    WAREHOUSE = EV_DEMO_WH
AS
SELECT
    MAKE,
    MODEL,
    EV_TYPE_SHORT,
    COUNT(*) AS TOTAL_REGISTRATIONS,
    COUNT(DISTINCT STATE) AS STATES_PRESENT,
    COUNT(DISTINCT COUNTY) AS COUNTIES_PRESENT,
    AVG(ELECTRIC_RANGE) AS AVG_RANGE,
    AVG(BASE_MSRP) AS AVG_MSRP,
    MIN(MODEL_YEAR) AS EARLIEST_YEAR,
    MAX(MODEL_YEAR) AS LATEST_YEAR,
    ROUND(TOTAL_REGISTRATIONS * 100.0 / SUM(TOTAL_REGISTRATIONS) OVER (), 2) AS MARKET_SHARE_PCT
FROM EV_POPULATION_DB.GOLD.FACT_EV_REGISTRATIONS
GROUP BY MAKE, MODEL, EV_TYPE_SHORT;
