-- ============================================================
-- agg_ev_yoy_growth.sql
-- Purpose: Year-over-year EV registration growth trends
-- Method: Dynamic Table on GOLD.FACT_EV_REGISTRATIONS
-- ============================================================

USE ROLE EV_DEMO_ADMIN;
USE WAREHOUSE EV_DEMO_WH;

CREATE OR REPLACE DYNAMIC TABLE EV_POPULATION_DB.GOLD.AGG_EV_YOY_GROWTH
    TARGET_LAG = '1 hour'
    WAREHOUSE = EV_DEMO_WH
AS
SELECT
    MODEL_YEAR,
    COUNT(*) AS REGISTRATIONS,
    COUNT_IF(EV_TYPE_SHORT = 'BEV') AS BEV_COUNT,
    COUNT_IF(EV_TYPE_SHORT = 'PHEV') AS PHEV_COUNT,
    LAG(COUNT(*)) OVER (ORDER BY MODEL_YEAR) AS PREV_YEAR_REGISTRATIONS,
    ROUND((COUNT(*) - PREV_YEAR_REGISTRATIONS) * 100.0 / NULLIF(PREV_YEAR_REGISTRATIONS, 0), 1) AS YOY_GROWTH_PCT,
    COUNT(DISTINCT MAKE) AS UNIQUE_MAKES,
    COUNT(DISTINCT MODEL) AS UNIQUE_MODELS,
    AVG(ELECTRIC_RANGE) AS AVG_RANGE,
    COUNT_IF(IS_CAFV_ELIGIBLE) AS CAFV_ELIGIBLE
FROM EV_POPULATION_DB.GOLD.FACT_EV_REGISTRATIONS
WHERE MODEL_YEAR BETWEEN 2010 AND 2025
GROUP BY MODEL_YEAR;
