-- ============================================================
-- agg_ev_charging_coverage.sql
-- Purpose: Enrichment — EVs joined with charging station coverage
-- Method: Dynamic Table joining FACT + DIM
-- ============================================================

USE ROLE EV_DEMO_ADMIN;
USE WAREHOUSE EV_DEMO_WH;

CREATE OR REPLACE DYNAMIC TABLE EV_POPULATION_DB.GOLD.AGG_EV_CHARGING_COVERAGE
    TARGET_LAG = '1 hour'
    WAREHOUSE = EV_DEMO_WH
AS
SELECT
    ev.STATE,
    ev.COUNTY,
    ev.CITY,
    COUNT(DISTINCT ev.VIN) AS TOTAL_EVS,
    COUNT(DISTINCT cs.STATION_ID) AS CHARGING_STATIONS,
    SUM(cs.NUM_PORTS) AS TOTAL_CHARGING_PORTS,
    ROUND(COUNT(DISTINCT ev.VIN)::FLOAT / GREATEST(COUNT(DISTINCT cs.STATION_ID), 1), 1) AS EVS_PER_STATION,
    ROUND(COUNT(DISTINCT ev.VIN)::FLOAT / GREATEST(SUM(cs.NUM_PORTS), 1), 1) AS EVS_PER_PORT,
    MAX(cs.POWER_LEVEL_KW) AS MAX_POWER_KW,
    ARRAY_AGG(DISTINCT cs.NETWORK) AS NETWORKS_AVAILABLE,
    CASE
        WHEN COUNT(DISTINCT cs.STATION_ID) = 0 THEN 'No Coverage'
        WHEN COUNT(DISTINCT ev.VIN)::FLOAT / GREATEST(SUM(cs.NUM_PORTS), 1) > 50 THEN 'Under-served'
        WHEN COUNT(DISTINCT ev.VIN)::FLOAT / GREATEST(SUM(cs.NUM_PORTS), 1) > 20 THEN 'Moderate'
        ELSE 'Well-served'
    END AS COVERAGE_STATUS
FROM EV_POPULATION_DB.GOLD.FACT_EV_REGISTRATIONS ev
LEFT JOIN EV_POPULATION_DB.GOLD.DIM_CHARGING_STATIONS cs
    ON UPPER(ev.CITY) = UPPER(cs.CITY) AND ev.STATE = cs.STATE
GROUP BY ev.STATE, ev.COUNTY, ev.CITY;
